name: Qodana

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap
        with:
          results-dir: ${{ github.workspace }}/qodana
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: qodana
          path: ${{ github.workspace }}/qodana

